name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "YourStrong!Password" # Use a strong password

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for SQL Server to be ready
        run: |
          echo "Waiting for SQL Server to be ready..."
          sleep 20 # Give the container time to initialize

      - name: Run tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:sqlserver://localhost:1433;databaseName=testdb
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: password1234
